inventory:
  plugin: SimpleInventory
  options:
    host_file: inventory/hosts.yaml
    group_file: inventory/groups.yaml
    defaults_file: inventory/defaults.yaml
# Disable Nornir's own logging to avoid conflicts (Loguru handles it)
logging:
  enabled: false
